### ISSUE TITLE
Full VAT Posting

### ISSUE THREAD

**Issue by maveca** [AdriaticOrg/code#11]
[Full VAT Posting](https://github.com/AdriaticOrg/sdd/blob/master/features/FullVATPosting.md)

**Comment by jbucik** [comment]
When posting sample sale invoice, we get division by 0 exception, please fix.
![full_vat_posting_issue01-1](https://user-images.githubusercontent.com/42441699/45157131-7e9fe980-b1e0-11e8-9cd5-3e3470387a2a.png)
![full_vat_posting_issue01](https://user-images.githubusercontent.com/42441699/45157132-7e9fe980-b1e0-11e8-8751-7a48eb348547.png)

**Comment by 0xEE00** [comment]
This was resolved a few hours ago on V0.1 branch.
Try to pull latest version.

**Comment by jbucik** [comment]
QL, thanks

**Comment by JasnaPirnar** [comment]
When posting Sales or Purchase Invoice with setup for Full VAT posting, field Unrealized Amount is filled. Field should be 0,00.

![image](https://user-images.githubusercontent.com/42738964/45298391-a35dcf00-b508-11e8-984d-e5c438c7cdfb.png)
