### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by gregoral** [AdriaticOrg/code#9]
please add .gitignore to every branch if you don't already have one

**.gitignore**
```build
out
node_modules
*.vsix
*.app
npm-debug.log
.alpackages
.vscode/*
!.vscode/launch.json.default
```

**Comment by boych83** [comment]
We all will create our own branched xlf-file. This will also conflict every time when we'll try to merge branches. For now, I think we should also add the xlf-files in .gitignore.

**Comment by maveca** [comment]
But at the end we need those files. It's should behave same as code.

**Comment by boych83** [comment]
Then we should at least arrange names for all xlf files that will have fixed names e.g. code.SLV.xlf,... Then only content will differ and be merged afterwards. It will be easier for merging.
